language: cpp
install: cmake
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
compiler:
  - clang
  - gcc
notifications:
  recipients:
    - wuyanyi09@foxmail.com
  email:
    on_success: change
    on_failure: always
